# Generated by Django 6.0.4 on 2026-04-29 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('owner', models.CharField(max_length=200, null=True)),
                ('session_id', models.CharField(max_length=200, null=True)),
                ('session_name', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
